# Generated by Django 5.2.1 on 2025-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Lenguaje', 'Lenguaje'), ('Humanidades', 'Humanidades'), ('Informática', 'Informática')], max_length=50)),
                ('enlace', models.URLField(blank=True)),
                ('portada', models.ImageField(blank=True, upload_to='portadas/')),
            ],
        ),
    ]
