# Generated by Django 5.2.1 on 2025-05-29 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_curso_fin_curso_inicio_alter_curso_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorprofile',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='carga',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='consiente_datos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='curso_dictar',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='experiencia',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='horario',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='institucion',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='modalidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='nivel_curso',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='nivel_educativo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesorprofile',
            name='titulo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
